spring:
  application:
    name: safe-community-centers-back

  data:
    mongodb:
      host: localhost
      port: 27017
      database: db-safe-hub

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
