services:
  app-scc-phoebus:
    container_name: app-scc-phoebus
    image: desafio/app-scc:0.1.0
    restart: always
    depends_on:
      - mongodb
      - rabbitmq
    ports:
      - "8080:8080"

  mongodb:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db-mongodb_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/

volumes:
  db-mongodb_data:
  rabbitmq_data:
  rabbitmq_log:
