services:
  mongodb:
    image: mongo:latest
    container_name: db
    ports:
      - "27017:27017"
    volumes:
      - db-mongodb_data:/data/db
    networks:
      - nt

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - nt

volumes:
  db-mongodb_data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  nt:
    driver: bridge
